/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controller.*;
import java.awt.Rectangle;
import java.io.File;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartPanel;
import org.jvnet.substance.SubstanceLookAndFeel;

/**
 *
 * @author ArandiLopez
 */
public class VistaProyecto extends javax.swing.JFrame {
    
    //Atributos nuevos
    private File raiz, separado;
    private ArrayList<String> lista;
    private ControllerDAO controlDao;
    private InternalSortController controlInterno;
    private ExternalSortController controlExterno;
    
    public File getRaiz(){
        return this.raiz;
    }
    
    public void setRaiz(File raiz){
        this.raiz = raiz;
    }

    public File getSeparado() {
        return separado;
    }

    public void setSeparado(File separado) {
        this.separado = separado;
    }
    

    /**
     * Creates new form VistaProyecto
     */
    public VistaProyecto() {

        
        initComponents();
        nombreDocLb.setText("         ");
        controlDao = new ControllerDAO();
        controlInterno = new InternalSortController();
        controlExterno = new ExternalSortController();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        TabPane = new javax.swing.JTabbedPane();
        internoPanel = new javax.swing.JPanel();
        ordenarInternoBtn = new javax.swing.JButton();
        shellPanel = new javax.swing.JPanel();
        ordenarShellBtn = new javax.swing.JButton();
        externoPanel = new javax.swing.JPanel();
        ordenarExternoBtn = new javax.swing.JButton();
        cargarArchivoBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        nombreDocLb = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cerrarBtn = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        salirMenu = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        licenciaMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Algoritmos de Ordenacion");
        setPreferredSize(new java.awt.Dimension(600, 480));
        setResizable(false);

        TabPane.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        TabPane.setName("JTabbedPane");

        ordenarInternoBtn.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        ordenarInternoBtn.setText("Ordenar");
        ordenarInternoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordenarInternoBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout internoPanelLayout = new javax.swing.GroupLayout(internoPanel);
        internoPanel.setLayout(internoPanelLayout);
        internoPanelLayout.setHorizontalGroup(
            internoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(internoPanelLayout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(ordenarInternoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(146, Short.MAX_VALUE))
        );
        internoPanelLayout.setVerticalGroup(
            internoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(internoPanelLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(ordenarInternoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        TabPane.addTab("Interno", internoPanel);

        ordenarShellBtn.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        ordenarShellBtn.setText("Ordenar");
        ordenarShellBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordenarShellBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout shellPanelLayout = new javax.swing.GroupLayout(shellPanel);
        shellPanel.setLayout(shellPanelLayout);
        shellPanelLayout.setHorizontalGroup(
            shellPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shellPanelLayout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(ordenarShellBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(147, Short.MAX_VALUE))
        );
        shellPanelLayout.setVerticalGroup(
            shellPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shellPanelLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(ordenarShellBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        TabPane.addTab("Shellsort", shellPanel);

        externoPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ordenarExternoBtn.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        ordenarExternoBtn.setText("Ordenar");
        ordenarExternoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordenarExternoBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout externoPanelLayout = new javax.swing.GroupLayout(externoPanel);
        externoPanel.setLayout(externoPanelLayout);
        externoPanelLayout.setHorizontalGroup(
            externoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(externoPanelLayout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(ordenarExternoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(147, Short.MAX_VALUE))
        );
        externoPanelLayout.setVerticalGroup(
            externoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(externoPanelLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(ordenarExternoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        TabPane.addTab("Externo", externoPanel);

        cargarArchivoBtn.setText("Cargar Archivo");
        cargarArchivoBtn.setToolTipText("Presione para cargar un archivo de texto que desee ordenar");
        cargarArchivoBtn.setName("");
        cargarArchivoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarArchivoBtnActionPerformed(evt);
            }
        });

        nombreDocLb.setText("NombreDocumento:");

        jLabel9.setText("Archivo Cargado:");

        cerrarBtn.setText("Cerrar");
        cerrarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarBtnActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        salirMenu.setText("Salir");
        salirMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirMenuActionPerformed(evt);
            }
        });
        jMenu1.add(salirMenu);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("About");

        licenciaMenu.setText("Licencia");
        licenciaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                licenciaMenuActionPerformed(evt);
            }
        });
        jMenu3.add(licenciaMenu);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cargarArchivoBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombreDocLb))
                    .addComponent(TabPane, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(338, 338, 338)
                .addComponent(jLabel3)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cerrarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(329, 329, 329))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(398, 398, 398))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nombreDocLb, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(cargarArchivoBtn)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TabPane, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(cerrarBtn)
                        .addGap(74, 74, 74))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void licenciaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_licenciaMenuActionPerformed
        // TODO add your handling code here:
        Licencia licencia = new Licencia(this, true);
        licencia.setVisible(true);

    }//GEN-LAST:event_licenciaMenuActionPerformed

    private void cargarArchivoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarArchivoBtnActionPerformed
        // TODO add your handling code here:
        ControlFilter controlFilter = new ControlFilter("Archivo de texto .txt", "txt");
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        chooser.setMultiSelectionEnabled(false);
        chooser.setCurrentDirectory(new File("./"));
        chooser.setFileFilter(controlFilter.getFilter());
        chooser.setAcceptAllFileFilterUsed(false);
        chooser.showOpenDialog(this);
        try {
            setRaiz(chooser.getSelectedFile());
            nombreDocLb.setText(getRaiz().getName());
            this.lista = controlDao.readFile(getRaiz());
            controlInterno.setArregloList(lista);
            this.separado = controlDao.writeFile(lista, "separado");
            JOptionPane.showMessageDialog(this, "¡Archivo cargado y separado con exito!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Archivo no cargado");
        }

    }//GEN-LAST:event_cargarArchivoBtnActionPerformed

    private void salirMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirMenuActionPerformed
        // TODO add your handling code here:

        System.exit(0);

    }//GEN-LAST:event_salirMenuActionPerformed

    private void cerrarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarBtnActionPerformed
        // TODO add your handling code here:
        System.exit(0);

    }//GEN-LAST:event_cerrarBtnActionPerformed

    private void ordenarInternoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordenarInternoBtnActionPerformed
        // TODO add your handling code here:
        Graficador graficador;
        graficador = new Graficador("Ordenacion Interna","Algoritmos de Ordenacion Interna","Milisegundos");
        graficador.setData(controlInterno.getMilisInsercion(), "Milisegundos", "Insercion");
        graficador.setData(controlInterno.getMilisBurbujaMenor(), "Milisegundos", "Burbuja Menor");
        graficador.setData(controlInterno.getMilisBurbujaMayor(), "Milisegundos", "Burbuja Mayor");
        graficador.setData(controlInterno.getMilisMergeSort(), "Milisegundos", "Mergesort");
        graficador.setData(controlInterno.getMilisQuickSort(), "Milisegundos", "Quicksort");
        graficador.drawGraphics();
        
    }//GEN-LAST:event_ordenarInternoBtnActionPerformed

    private void ordenarShellBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordenarShellBtnActionPerformed
        // TODO add your handling code here:
        Graficador graficador;
        graficador = new Graficador("Ordenacion por Shellsort","Algoritmos de Shellsort","Milisegundos");
    }//GEN-LAST:event_ordenarShellBtnActionPerformed

    private void ordenarExternoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordenarExternoBtnActionPerformed
        // TODO add your handling code here:
        Graficador graficador = new Graficador("Ordenacion Externa","Algortimos de Ordenacion Externa","Milisegundos");
    }//GEN-LAST:event_ordenarExternoBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {


        SubstanceLookAndFeel.setSkin("org.jvnet.substance.skin.RavenSkin");
        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new VistaProyecto().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane TabPane;
    private javax.swing.JButton cargarArchivoBtn;
    private javax.swing.JButton cerrarBtn;
    private javax.swing.JPanel externoPanel;
    private javax.swing.JPanel internoPanel;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JMenuItem licenciaMenu;
    private javax.swing.JLabel nombreDocLb;
    private javax.swing.JButton ordenarExternoBtn;
    private javax.swing.JButton ordenarInternoBtn;
    private javax.swing.JButton ordenarShellBtn;
    private javax.swing.JMenuItem salirMenu;
    private javax.swing.JPanel shellPanel;
    // End of variables declaration//GEN-END:variables
    
}
